name: Deploy CDK Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Run Tests
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          . .venv/bin/activate
          pytest -vv

      # - name: Deploy CDK Stack
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      #   run: |
      #     . .venv/bin/activate
      #     cdk bootstrap
      #     cdk deploy --all --require-approval never
